### ISSUE TITLE
Issue building dwarffortress

### ISSUE THREAD

**Issue by laissezfarrell** [DockerDemos/DwarfFortressServer#6]
Hi - 

When attempting to build from Dockerfile, I get the following snippet:

Step 12 : RUN curl -ssL http://www.bay12games.com/dwarves/df_40_24_linux.tar.bz2 | tar -xj
 ---> Running in 8c294a62e186
2015/05/04 19:08:16 /var/lib/docker/aufs/mnt/8c294a62e186941600d9198525fdc6a07e8a2e63a71afbc3698dae3099bec37b is not within /var/lib/docker/aufs/mnt/8c294a62e186941600d9198525fdc6a07e8a2e63a71afbc3698dae3099bec37b

Not sure if I have something configured incorrectly or if I'm missing something else.

**Comment by laissezfarrell** [comment]
Hey. Upgraded Docker and everything builds fine!

**Comment by clcollins** [comment]
Great!  (Sorry, didn't see the notice about this ticket till just now!)
